---
- name: AWS - VPC and subnet
  hosts: localhost
  connection: local
  gather_facts: false

  vars:
    aws_region: ap-south-1

  tasks:

    - name: Create VPC
      amazon.aws.ec2_vpc_net:
        name: ansible-demo-vpc
        cidr_block: 10.20.0.0/16
        region: "{{ aws_region }}"
        state: present
      register: vpc

    - name: Create subnet
      amazon.aws.ec2_vpc_subnet:
        vpc_id: "{{ vpc.vpc.id }}"
        cidr: 10.20.1.0/24
        region: "{{ aws_region }}"
        az: "{{ aws_region }}a"
        tags:
          Name: ansible-demo-subnet
        state: present
      register: subnet

    - name: Create second subnet
      amazon.aws.ec2_vpc_subnet:
        vpc_id: "{{ vpc.vpc.id }}"
        cidr: 10.20.2.0/24
        az: "{{ aws_region }}b"
        region: "{{ aws_region }}"
        tags:
          Name: ansible-demo-subnet-2
        state: present
      register: subnet2

    - name: Show VPC
      debug:
        var: vpc.vpc.id

    - name: Show subnet
      debug:
        var: subnet.subnet.id

    - name: Show second subnet
      ansible.builtin.debug:
        var: subnet2.subnet.id