---
- name: Create Azure Resource Group
  hosts: localhost
  connection: local
  gather_facts: false

  vars:
    azure_client_id: "{{ lookup('env', 'AZURE_CLIENT_ID') }}"
    azure_secret: "{{ lookup('env', 'AZURE_SECRET') }}"
    azure_tenant: "{{ lookup('env', 'AZURE_TENANT') }}"
    azure_subscription_id: "{{ lookup('env', 'AZURE_SUBSCRIPTION_ID') }}"
  
  tasks:
    - name: Log in to Azure using az login
      shell: |
        az login --service-principal \
                 --username "{{ azure_client_id }}" \
                 --password "{{ azure_secret }}" \
                 --tenant "{{ azure_tenant }}"
      register: login_output

    - name: Set default subscription
      shell: az account set --subscription "{{ azure_subscription_id }}"
      when: login_output.rc == 0

    - name: Show current Azure account
      shell: az account show
      register: az_account
      changed_when: false

    - debug:
        var: az_account.stdout



    - name: Create a resource group named 'RG-AWX'
      azure.azcollection.azure_rm_resourcegroup:
        name: RG-AWX
        location: eastus



