---
- name: Create Azure Resource Group
  hosts: localhost
  connection: local
  gather_facts: false
  
  tasks:
    - name: Display AZURE_CLIENT_ID
      debug:
        msg: "AZURE_CLIENT_ID = {{ AZURE_CLIENT_ID }}"

    - name: Display AZURE_TENANT
      debug:
        msg: "AZURE_TENANT = {{ AZURE_TENANT }}"

    - name: Display AZURE_SUBSCRIPTION_ID
      debug:
        msg: "AZURE_SUBSCRIPTION_ID = {{ AZURE_SUBSCRIPTION_ID }}"

    - name: Display AZURE_SECRET (only for debug - remove in production)
      debug:
        msg: "AZURE_SECRET = {{ AZURE_SECRET }}"
      no_log: false  # Set to true before production

    - name: Set MSAL env
      shell: |
        echo $AZURE_CORE_USE_MSAL_HTTP_CACHE
      environment:
        AZURE_CORE_USE_MSAL_HTTP_CACHE=false

    - name: Log in to Azure using az login
      shell: |
        az login --service-principal -u "{{ AZURE_CLIENT_ID }}" -p "{{ AZURE_SECRET }}" --tenant "{{ AZURE_TENANT }}"
      environment:
        AZURE_CLIENT_ID: "{{ AZURE_CLIENT_ID }}"
        AZURE_SECRET: "{{ AZURE_SECRET }}"
        AZURE_TENANT: "{{ AZURE_TENANT }}"
        AZURE_SUBSCRIPTION_ID: "{{ AZURE_SUBSCRIPTION_ID }}"
      register: login_output

    - name: Set default subscription
      shell: az account set --subscription "{{ AZURE_SUBSCRIPTION_ID }}"
      when: login_output.rc == 0

    - name: Show current Azure account
      shell: az account show
      register: az_account
      changed_when: false

    - debug:
        var: az_account.stdout



    - name: Create a resource group named 'RG-AWX'
      azure.azcollection.azure_rm_resourcegroup:
        name: RG-AWX
        location: eastus



