---
- name: AWS - Routing and Connectivity
  hosts: localhost
  connection: local
  gather_facts: false

  vars_files:
    - vars/aws.yml

  tasks:

    - name: Create Internet Gateway
      amazon.aws.ec2_vpc_igw:
        vpc_id: "{{ vpc_id }}"
        region: "{{ aws_region }}"
        state: present
      register: igw

    - name: Create default route
      amazon.aws.ec2_vpc_route_table:
        vpc_id: "{{ vpc_id }}"
        region: "{{ aws_region }}"
        subnets:
          - "{{ subnet_id }}"
        routes:
          - dest: 0.0.0.0/0
            gateway_id: "{{ lookup('amazon.aws.aws_gateway_facts', region=aws_region) }}"
        state: present

    - name: Show igw
      debug:
        var: igw.igw.id