---
- name: Provision AWS Site-to-Site VPN
  hosts: localhost
  connection: local
  gather_facts: false

  tasks:

    - name: Create Customer Gateway
      community.aws.ec2_customer_gateway:
        name: ansible-course-cgw
        ip_address: "{{ customer_gateway_ip }}"
        bgp_asn: 65000
        routing: static
        state: present
        region: "{{ aws_region }}"
      register: cgw

    - name: Display complete Customer Gateway result
      ansible.builtin.debug:
        var: cgw