---
    - name: EE validation - list resource groups
      hosts: localhost
      connection: local
      tasks:
        - name: Confirm Azure module works end-to-end
          azure.azcollection.azure_rm_resourcegroup_info:
          register: rg_check

        - name: Show result
          ansible.builtin.debug:
            var: rg_check