---
- name: Check AWS Ansible Environment
  hosts: localhost
  connection: local
  gather_facts: false

  tasks:
    - name: Ansible version
      command: ansible --version
      register: ansible_ver
      changed_when: false

    - name: AWS collection version
      command: ansible-galaxy collection list amazon.aws
      register: aws_collection
      changed_when: false

    - name: Display
      debug:
        msg:
          - "{{ ansible_ver.stdout_lines }}"
          - "{{ aws_collection.stdout_lines }}"