- name: Hello World Sample
  hosts: dc01
  gather_facts: false
  tasks:
    - name: Hello Message
      debug:
        msg: "Hello World!"

    - name: Execute PowerShell command
      win_shell: |
        Write-Host "Hello World from DC01 server!"
        register: result

    - name: Show command output
      debug:
        var: result.stdout
