- name: Hello World Sample
  hosts: dc01
  gather_facts: false
  tasks:
    - name: Hello Message
      debug:
        msg: "Hello World!"

    - name: Get hostname
      ansible.windows.win_hostname:

    - name: Get hostname
      win_shell: |
        Write-Host "Hello World from Uzair!"
