---
- name: Verify EE
  hosts: localhost
  gather_facts: false

  tasks:

    - name: Show Ansible version
      command: ansible --version
      register: ansible_version

    - debug:
        var: ansible_version.stdout_lines

    - name: Show collections
      command: ansible-galaxy collection list
      register: collections

    - debug:
        var: collections.stdout_lines