---
collections:
  - name: community.docker
    version: "4.6.1"
  - name: kubernetes.core
    version: "5.3.0"
  - name: junipernetworks.junos
    version: "9.1.0"
  - name: azure.azcollection
    version: "3.4.0"