- name: Display server hostname and IP address
  hosts: all
  gather_facts: no
  tasks:
    - name: Get hostname
      win_shell: |
        hostname
      register: hostname_output

    - name: Show hostname
      debug:
        var: hostname_output.stdout_lines
   
    
    - name: Get IP Address
      win_shell: |
        (Get-NetIPAddress -AddressFamily IPv4).IPAddress
      register: ip_address_output

    - name: Show IP Address
      debug:
        var: ip_address_output.stdout_lines

