---
- hosts: vyos
  gather_facts: false

  tasks:
    - name: Show version
      vyos.vyos.vyos_command:
        commands:
          - show version
      register: output

    - debug:
        var: output.stdout_lines